"""Simple Agent Lab core runtime.

Preset agents (the bash agent and friends) live under
`simple_agent_lab.agents.*` — they are downstream consumers of this
package's protocol/runtime/LLM/tool layers, not part of the core
surface. Import them explicitly, e.g.::

    from simple_agent_lab.agents.bash import make_bash_use_agent
"""

from .core import (
    Agent,
    Event,
    EventKind,
    NextFn,
    State,
    StepFn,
    TransformFn,
    build_agent_context_view,
    context_view,
    dispatch_tool_calls,
    make_message,
    make_llm_step,
    run,
    sequence,
    until_final,
)
from .context_view import (
    ContextPolicy,
    ContextStats,
    ContextView,
    build_context_view,
    clip_message,
    estimate_message_chars,
    estimate_message_tokens,
    is_visible_to_agent,
)
from .messages import (
    AssistantMessage,
    AgentName,
    ContentBlock,
    ImageBlock,
    Message,
    MessageChannel,
    MessageContent,
    MessageKind,
    Role,
    SystemMessage,
    TextBlock,
    ThinkingBlock,
    TokenUsage,
    ToolCallBlock,
    ToolResultBlock,
    UserMessage,
    assistant_message,
    is_tool_result_message,
    message_text,
    message_tool_calls,
    system_message,
    text_of,
    thinking_blocks_of,
    tool_calls_of,
    tool_result_message,
    tool_results_message,
    tool_results_of,
    user_message,
)
from .openai_training import append_openai_training_record, openai_training_record
from .runtime import AgentRuntime, Listener, print_trace
from .tools import (
    AbortFlag,
    AgentTool,
    Tool,
    ToolExecutionMode,
    ToolResult,
    ToolUpdateFn,
    text_result,
    tool_result_text,
)

__all__ = [
    "Agent",
    "AgentRuntime",
    "Event",
    "EventKind",
    "Listener",
    "NextFn",
    "StepFn",
    "TransformFn",
    "AssistantMessage",
    "AgentName",
    "ContentBlock",
    "ImageBlock",
    "Message",
    "MessageChannel",
    "MessageContent",
    "MessageKind",
    "Role",
    "SystemMessage",
    "TextBlock",
    "ThinkingBlock",
    "TokenUsage",
    "ToolCallBlock",
    "ToolResultBlock",
    "UserMessage",
    "is_tool_result_message",
    "text_of",
    "thinking_blocks_of",
    "tool_calls_of",
    "tool_results_of",
    "State",
    "ContextPolicy",
    "ContextStats",
    "ContextView",
    "assistant_message",
    "build_agent_context_view",
    "build_context_view",
    "clip_message",
    "context_view",
    "dispatch_tool_calls",
    "estimate_message_chars",
    "estimate_message_tokens",
    "is_visible_to_agent",
    "make_message",
    "make_llm_step",
    "message_text",
    "message_tool_calls",
    "print_trace",
    "run",
    "append_openai_training_record",
    "openai_training_record",
    "sequence",
    "system_message",
    "tool_result_message",
    "tool_results_message",
    "until_final",
    "user_message",
    "AbortFlag",
    "AgentTool",
    "Tool",
    "ToolExecutionMode",
    "ToolResult",
    "ToolUpdateFn",
    "text_result",
    "tool_result_text",
]
