"""Simple Agent Lab core runtime.

Preset agents (the bash agent and friends) live under
`simple_agent_lab.agents.*` — they are downstream consumers of this
package's protocol/runtime/LLM/tool layers, not part of the core
surface. Import them explicitly, e.g.::

    from simple_agent_lab.agents.bash import make_bash_agent
"""

from .core import (
    Agent,
    GenerateFn,
    dispatch_tool_calls,
    run,
)
from .state import State, StateSnapshot
from .llm_agent import make_llm_agent
from .messages import make_message
from .protocols import (
    AgentEndEvent,
    AgentStartEvent,
    ContextCompressionEvent,
    Event,
    EventKind,
    MessageEvent,
    ModelRequestEvent,
    ModelResponseEvent,
    RuntimeEvent,
    ToolExecutionEndEvent,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    TurnEndEvent,
    TurnStartEvent,
)
from .context_view import (
    ContextPolicy,
    ContextStats,
    ContextView,
    build_context_view,
    clip_message,
    estimate_context_tokens,
    estimate_message_chars,
    estimate_message_tokens,
)
from .messages import (
    AssistantMessage,
    AgentName,
    ContentBlock,
    ImageBlock,
    Message,
    MessageChannel,
    MessageContent,
    MessageKind,
    Role,
    SystemMessage,
    TextBlock,
    ThinkingBlock,
    TokenUsage,
    ToolCallBlock,
    ToolResultBlock,
    UserMessage,
    assistant_message,
    is_tool_result_message,
    message_text,
    message_tool_calls,
    system_message,
    text_of,
    thinking_blocks_of,
    tool_calls_of,
    tool_result_message,
    tool_results_message,
    tool_results_of,
    user_message,
)
from .trace import append_openai_training_record, openai_training_record, print_trace
from .trajectory import event_record, model_turns_from_events, run_trace_from_state
from .tools import (
    AbortFlag,
    AgentTool,
    Tool,
    ToolExecutionMode,
    ToolResult,
    ToolUpdateFn,
    task_tool,
    text_result,
    tool_result_text,
)

__all__ = [
    "Agent",
    "AgentEndEvent",
    "AgentStartEvent",
    "ContextCompressionEvent",
    "Event",
    "EventKind",
    "MessageEvent",
    "ModelRequestEvent",
    "ModelResponseEvent",
    "GenerateFn",
    "RuntimeEvent",
    "ToolExecutionEndEvent",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "TurnEndEvent",
    "TurnStartEvent",
    "AssistantMessage",
    "AgentName",
    "ContentBlock",
    "ImageBlock",
    "Message",
    "MessageChannel",
    "MessageContent",
    "MessageKind",
    "Role",
    "SystemMessage",
    "TextBlock",
    "ThinkingBlock",
    "TokenUsage",
    "ToolCallBlock",
    "ToolResultBlock",
    "UserMessage",
    "is_tool_result_message",
    "text_of",
    "thinking_blocks_of",
    "tool_calls_of",
    "tool_results_of",
    "State",
    "StateSnapshot",
    "ContextPolicy",
    "ContextStats",
    "ContextView",
    "assistant_message",
    "build_context_view",
    "clip_message",
    "dispatch_tool_calls",
    "estimate_context_tokens",
    "estimate_message_chars",
    "estimate_message_tokens",
    "make_message",
    "make_llm_agent",
    "message_text",
    "message_tool_calls",
    "print_trace",
    "run",
    "event_record",
    "model_turns_from_events",
    "run_trace_from_state",
    "append_openai_training_record",
    "openai_training_record",
    "system_message",
    "task_tool",
    "tool_result_message",
    "tool_results_message",
    "user_message",
    "AbortFlag",
    "AgentTool",
    "Tool",
    "ToolExecutionMode",
    "ToolResult",
    "ToolUpdateFn",
    "text_result",
    "tool_result_text",
]
