"""Simple Long Horizon Agent core runtime.

Preset agents (the bash agent and friends) live under
`simple_long_horizon_agent.agents.*` — they are downstream consumers of this
package's protocol/runtime/LLM/tool layers, not part of the core
surface. Import them explicitly, e.g.::

    from simple_long_horizon_agent.agents.starter import make_bash_agent
"""

from .core import Agent, run
from .state import State
from .llm_agent import make_llm_agent
from .messages import make_message
from .protocols import (
    AgentEndEvent,
    AgentStartEvent,
    ContextCompressionEvent,
    Event,
    EventKind,
    HookFiredEvent,
    MessageEvent,
    ModelRequestEvent,
    ModelResponseEvent,
    ToolExecutionEndEvent,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    TurnEndEvent,
    TurnStartEvent,
)
from .hooks import (
    HookContext,
    HookDecision,
    HookPoint,
)
from .compression import (
    CompactControl,
    SummarizeStrategy,
    TieredStrategy,
    ToolCompactStrategy,
    make_compact_control,
)
from .context_view import (
    CompressionDecision,
    CompressionStrategy,
    ContextPolicy,
    ContextView,
    build_context_view,
    effective_token_budget,
    estimate_context_tokens,
    estimate_message_chars,
    estimate_message_tokens,
)
from .messages import (
    AssistantMessage,
    AgentName,
    ContentBlock,
    ImageBlock,
    Message,
    MessageContent,
    MessageKind,
    MessageSidecar,
    Role,
    RuntimeMessage,
    TextBlock,
    ThinkingBlock,
    TokenUsage,
    ToolCallBlock,
    ToolResultBlock,
    UserMessage,
    assistant_message,
    is_tool_result_message,
    message_text,
    runtime_message,
    text_of,
    tool_result_message,
    tool_results_message,
    tool_results_of,
    user_message,
)
from .model_metadata import (
    ContextWindowBook,
    CostBreakdown,
    ModelCost,
    ModelPrice,
    PriceBook,
    RunCost,
    default_context_window_book,
    default_price_book,
    usage_cost,
)
from .trace import (
    ModelTurn,
    RunTrace,
    Span,
    append_openai_training_record,
    event_record,
    model_turns_from_events,
    openai_training_record,
    print_trace,
    run_trace_from_state,
    spans_from_events,
)
from .tools import (
    AbortFlag,
    AgentTool,
    Tool,
    ToolExecutionMode,
    ToolResult,
    ToolUpdateFn,
    task_tool,
    text_result,
    tool_result_text,
)
from .tools.read import make_read_tool
from .tools.edit import make_edit_tool
from .tools.recall import make_recall_tool
from .skills import (
    SkillMetadata,
    SkillRoot,
    discover_skills,
    render_skills_instructions,
    run_with_skills,
)

__all__ = [
    "Agent",
    "AgentEndEvent",
    "AgentStartEvent",
    "ContextCompressionEvent",
    "Event",
    "EventKind",
    "HookContext",
    "HookDecision",
    "HookFiredEvent",
    "HookPoint",
    "MessageEvent",
    "ModelRequestEvent",
    "ModelResponseEvent",
    "ToolExecutionEndEvent",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "TurnEndEvent",
    "TurnStartEvent",
    "AssistantMessage",
    "AgentName",
    "ContentBlock",
    "ImageBlock",
    "Message",
    "MessageContent",
    "MessageKind",
    "MessageSidecar",
    "Role",
    "RuntimeMessage",
    "TextBlock",
    "ThinkingBlock",
    "TokenUsage",
    "ToolCallBlock",
    "ToolResultBlock",
    "UserMessage",
    "is_tool_result_message",
    "text_of",
    "tool_results_of",
    "State",
    "CompactControl",
    "CompressionDecision",
    "CompressionStrategy",
    "ContextPolicy",
    "ContextView",
    "SummarizeStrategy",
    "TieredStrategy",
    "ToolCompactStrategy",
    "make_compact_control",
    "assistant_message",
    "build_context_view",
    "effective_token_budget",
    "estimate_context_tokens",
    "estimate_message_chars",
    "estimate_message_tokens",
    "make_message",
    "make_llm_agent",
    "message_text",
    "print_trace",
    "run",
    "ModelTurn",
    "RunTrace",
    "Span",
    "event_record",
    "model_turns_from_events",
    "run_trace_from_state",
    "spans_from_events",
    "append_openai_training_record",
    "openai_training_record",
    "CostBreakdown",
    "ContextWindowBook",
    "ModelCost",
    "ModelPrice",
    "PriceBook",
    "RunCost",
    "default_context_window_book",
    "default_price_book",
    "usage_cost",
    "runtime_message",
    "task_tool",
    "tool_result_message",
    "tool_results_message",
    "user_message",
    "AbortFlag",
    "AgentTool",
    "Tool",
    "ToolExecutionMode",
    "ToolResult",
    "ToolUpdateFn",
    "text_result",
    "tool_result_text",
    "make_read_tool",
    "make_edit_tool",
    "make_recall_tool",
    "SkillMetadata",
    "SkillRoot",
    "discover_skills",
    "render_skills_instructions",
    "run_with_skills",
]
