#!/usr/bin/env python3
"""Regenerate the decision-record index in README.md from each ADR's front-matter.

Run after adding or editing a decision record:

    python docs/decisions/build_index.py

The index between the BEGIN/END INDEX markers in README.md is generated; do not
edit it by hand. Each ADR is a Markdown file named ``YYYYMMDD-slug.md`` with a
YAML-ish front-matter block:

    ---
    title: "Tool Results Are Content Blocks, Not a Separate Message Role"
    status: Accepted
    date: 2026-05-12
    slug: tool-result-as-content-block
    note: "tool-result fragment superseded by `tool-result-as-content-block`"
    ---

``status`` is one of Accepted / Proposed / Withdrawn. ``note`` is optional.
"""

from __future__ import annotations

import sys
from pathlib import Path

DECISIONS_DIR = Path(__file__).resolve().parent
README = DECISIONS_DIR / "README.md"
BEGIN = "<!-- BEGIN INDEX: generated by build_index.py; do not edit by hand -->"
END = "<!-- END INDEX -->"
STATUS_ORDER = ["Accepted", "Proposed", "Withdrawn"]


def _unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1].replace('\\"', '"').replace("\\'", "'")
    return value


def parse_front_matter(text: str) -> dict[str, str]:
    """Parse the leading ``---`` fenced block as flat ``key: value`` pairs."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    meta: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        meta[key.strip()] = _unquote(value)
    return meta


def collect() -> list[dict[str, str]]:
    records = []
    for path in DECISIONS_DIR.glob("*.md"):
        if path.name in {"README.md", "template.md"}:
            continue
        meta = parse_front_matter(path.read_text(encoding="utf-8"))
        if not meta.get("title") or not meta.get("status"):
            raise SystemExit(f"{path.name}: missing title/status front-matter")
        meta["file"] = path.name
        records.append(meta)
    return records


def render_index(records: list[dict[str, str]]) -> str:
    out: list[str] = []
    for status in STATUS_ORDER:
        group = sorted(
            (r for r in records if r["status"] == status),
            key=lambda r: (r.get("date", ""), r["slug"]),
        )
        if not group:
            continue
        out.append(f"## {status}")
        out.append("")
        for r in group:
            line = f"- [{r['title']}]({r['file']})"
            if r.get("note"):
                line += f" — {r['note']}"
            out.append(line)
        out.append("")
    unknown = sorted({r["status"] for r in records} - set(STATUS_ORDER))
    if unknown:
        raise SystemExit(f"unknown status values: {', '.join(unknown)}")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    check = "--check" in (argv if argv is not None else sys.argv[1:])
    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise SystemExit("README.md is missing the BEGIN/END INDEX markers")
    head, _, rest = text.partition(BEGIN)
    _, _, tail = rest.partition(END)
    index = render_index(collect())
    new = f"{head}{BEGIN}\n\n{index}\n{END}{tail}"
    if check:
        if new != text:
            raise SystemExit(
                "docs/decisions/README.md index is stale.\n"
                "Run: python docs/decisions/build_index.py"
            )
        print("README.md index up to date")
        return 0
    if new != text:
        README.write_text(new, encoding="utf-8")
        print("README.md index regenerated")
    else:
        print("README.md index already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
